### PR TITLE
reverting version of grunt-noflo-browser and fbp-spec

### PR DESCRIPTION
**Pull request by dmtaub**
Needed to prevent built from failing. Still need to work towards a solution merging recent noflo-ui changes.

### CODE REVIEW

**Comment by glenna-m** [comment]
LGTM  - thanks for tracking this down, Daniel.

**Comment by dmtaub** [comment]
@dbooth-boston  ?

**Comment by dmtaub** [comment]
There were a lot of warnings in microflo. e.g. `WARNING in ./~/microflo/~/serialport/~/bindings/README.md` from direct CS inclusion in package.json . it's not included directly in the upstream noflo-ui, so I removed it here,too.

**Comment by glenna-m** [comment]
Reviewed and tested the latest.  This works though there are a couple of stack traces thrown along the way from Webpack trying to use markup files as source.  Would be good to clean that up in a future PR.  But this is a step forward, for now - thank you Daniel.  LGTM.

**Comment by dbooth-boston** [comment]
LGTM

**Pull request merged**
